// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadFile(arg1) {
  return window['go']['app']['App']['ReadFile'](arg1);
}

export function ShowOpenDialog() {
  return window['go']['app']['App']['ShowOpenDialog']();
}

export function ShowSaveDialog(arg1) {
  return window['go']['app']['App']['ShowSaveDialog'](arg1);
}

export function WriteFile(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['WriteFile'](arg1, arg2, arg3, arg4);
}
