// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmQuit() {
  return window['go']['app']['App']['ConfirmQuit']();
}

export function LoadSettings() {
  return window['go']['app']['App']['LoadSettings']();
}

export function ReadFile(arg1) {
  return window['go']['app']['App']['ReadFile'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function ShowOpenDialog() {
  return window['go']['app']['App']['ShowOpenDialog']();
}

export function ShowSaveDialog(arg1) {
  return window['go']['app']['App']['ShowSaveDialog'](arg1);
}

export function ShowWindow() {
  return window['go']['app']['App']['ShowWindow']();
}

export function SystemThemeIsDark() {
  return window['go']['app']['App']['SystemThemeIsDark']();
}

export function WriteFile(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['WriteFile'](arg1, arg2, arg3, arg4);
}
