// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ConfirmQuit():Promise<void>;

export function LoadSettings():Promise<app.Settings>;

export function ReadFile(arg1:string):Promise<app.FileContents>;

export function SaveSettings(arg1:app.Settings):Promise<void>;

export function ShowOpenDialog():Promise<Array<string>>;

export function ShowSaveDialog(arg1:string):Promise<string>;

export function WriteFile(arg1:string,arg2:string,arg3:app.Encoding,arg4:app.LineEnding):Promise<void>;
